name: flutter_ai_toolkit
description: >-
  A set of AI chat-related widgets for Flutter apps targeting
  mobile, desktop, and web.
version: 0.6.8
repository: https://github.com/flutter/ai

topics:
  - ai
  - chat
  - gemini

environment:
  sdk: ^3.5.0
  flutter: '>=3.27.0'

dependencies:
  cross_file: ^0.3.4+2
  file_selector: ^1.0.3
  firebase_vertexai: ^1.0.1
  flutter:
    sdk: flutter
  flutter_context_menu: ^0.2.0
  flutter_markdown: ^0.7.4+3
  flutter_picture_taker: ^0.2.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  image_picker: ^1.1.2
  mime: ^2.0.0
  universal_platform: ^1.1.0
  uuid: ^4.4.2
  waveform_recorder: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
   - family: FatIcons
     fonts:
      - asset: lib/fonts/FatIcons.ttf
